export const ROUTES = {
  login: 'Login',
  chooseLanguage: 'ChooseLanguage',
  chooseRole: 'ChooseRole',
  otpSend: 'OtpSend',
  otpVerification: 'OtpVerification',
  createDairy: 'CreateDairy',
  addDairy: 'AddDairy',
  onboarding: 'Onboarding',
  home: 'Home',
  order: 'Order',
  app: 'App',
  importContacts: 'Party Import',
  partyForm: 'partyForm',
  partyList: 'PartyList',
  customizePrice: 'CustomizePrice',
  selectItemParty: 'SelectItemParty',
  itemForm: 'ItemForm',
  itemList: 'ItemList',
  staffForm: 'StaffForm',
  staffList: 'StaffList',
  dairyPermission: 'DairyPermission',
  report: 'Report',
  dayBook: 'Day Book',
  cashBook: 'Cash Book',
  partyLedger: 'PartyLedger',
  voucherBook: 'VoucherBook',
  bankBook: 'BankBook',
  dairyCashBook: 'DairyCashBook',
  ledgerBook: 'Ledger Book',
  purchase: 'Purchase',
  sales: 'Sales',
  payment: 'Payment',
  receipt: 'Receipt',
  smartFilter: 'SmartFilter',
};

export const MODALS = {
  loader: 'Loader',
  network: 'Network',
  dropdown: 'Dropdown',
  selectFile: 'SelectFile',
  smsPrint: 'SmsPrint',
  customPrice: 'CustomPrice',
};
